name: eventnotifier
version: 1.1.0
description: Broadcasts named events to interested subscribers. When an event occurs, a method (callback) associated with the subscriber is executed.
homepage: https://github.com/aryehof/dart-eventnotifier

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
